'use client';
import { useMemo, useState } from 'react';
import { Song, combineSongLine } from '@/lib/releaseVoting';
export default function PublicVotingForm({roundId,roundTitle,placesCount,songs}:{roundId:string;roundTitle:string;placesCount:number;songs:Song[]}){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[insta,setInsta]=useState(''),[query,setQuery]=useState(''),[ranking,setRanking]=useState<(Song|null)[]>(Array.from({length:placesCount},()=>null)),[zonk,setZonk]=useState(''),[msg,setMsg]=useState<{type:string;text:string}|null>(null),[loading,setLoading]=useState(false);
 const rankedIds=ranking.filter(Boolean).map(s=>s!.id); const firstFree=ranking.findIndex(x=>!x); const available=useMemo(()=>songs.filter(s=>!rankedIds.includes(s.id) && combineSongLine(s).toLowerCase().includes(query.toLowerCase())),[songs,rankedIds.join(','),query]);
 function add(song:Song){ if(firstFree<0)return; setRanking(r=>{const n=[...r]; n[firstFree]=song; return n;}); }
 function remove(i:number){ setRanking(r=>{const n=[...r]; n[i]=null; return n;}); }
 function move(i:number,d:number){ const t=i+d; if(t<0||t>=ranking.length)return; setRanking(r=>{const n=[...r]; [n[i],n[t]]=[n[t],n[i]]; return n;}); }
 async function submit(e:React.FormEvent){ e.preventDefault(); setMsg(null); if(rankedIds.length!==placesCount){setMsg({type:'error',text:`Bitte belege alle ${placesCount} Plätze.`});return;} setLoading(true); try{ const payload=ranking.map((s,i)=>({songId:s!.id,points:placesCount-i})); const res=await fetch('/api/release-voting/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roundId,jurorName:name,jurorEmail:email,jurorInstagram:insta,ranking:payload,zonkSongId:zonk||null})}); const data=await res.json().catch(()=>null); if(!res.ok||!data?.ok) throw new Error(data?.error||'Ungültige Server-Antwort.'); setMsg({type:'success',text:'Fast geschafft: Bitte bestätige dein Voting über den Link in deiner E-Mail. Die Mail kann einige Minuten dauern. Prüfe bitte auch den Spam-Ordner.'}); setRanking(Array.from({length:placesCount},()=>null)); setName('');setEmail('');setInsta('');setZonk(''); }catch(err){ setMsg({type:'error',text:err instanceof Error?err.message:'Fehler beim Absenden.'}); } finally{setLoading(false);} }
 return <form onSubmit={submit} className="vote-form">{msg&&<div className={`notice ${msg.type}`}>{msg.text}</div>}<div className="input-grid"><label>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Dein Name"/></label><label>E-Mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="für Bestätigung"/></label><label>Instagram<input value={insta} onChange={e=>setInsta(e.target.value)} placeholder="optional"/></label></div><div className="vote-workspace"><section className="card"><h2>Songs</h2><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Suche nach Song oder Artist..."/><div className="song-list-scroll">{available.map(song=><div className="song-row" key={song.id}><button type="button" onClick={()=>add(song)}>{combineSongLine(song)}</button><button type="button" className="plus" onClick={()=>add(song)}>+</button></div>)}</div><small>{available.length} Songs verfügbar</small></section><section className="card"><h2>Deine Top 12 <span>{rankedIds.length}/{placesCount}</span></h2><div className="rank-list-scroll">{ranking.map((song,i)=><div className="rank-row" key={i}><b>{i+1}</b>{song?<span>{combineSongLine(song)}</span>:<em>Noch kein Song gewählt</em>}<div>{song&&<><button type="button" onClick={()=>move(i,-1)}>↑</button><button type="button" onClick={()=>move(i,1)}>↓</button><button type="button" onClick={()=>remove(i)}>×</button></>}</div></div>)}</div></section></div><section className="card zonk"><h3>ZONK – Song der Woche <small>(optional)</small></h3><p>Wähle hier den schlechtesten Song der Woche.</p><select value={zonk} onChange={e=>setZonk(e.target.value)}><option value="">Keinen ZONK wählen</option>{songs.map(s=><option key={s.id} value={s.id}>{combineSongLine(s)}</option>)}</select></section><button className="submit" disabled={loading||rankedIds.length!==placesCount}>{loading?'Sendet…':'Stimme per E-Mail bestätigen & absenden'}</button></form>
}
