// Seed-Daten aus der Live-Auftritte-Künstlerverwaltung, Export 2026-09-06.
// Einmalig in app_settings übernommen; danach sind Änderungen im Release-Check maßgeblich.
export const RELEASE_ARTIST_INSTAGRAM_SEED_VERSION = 'live-auftritte-2026-09-06-v1';

export const RELEASE_ARTIST_INSTAGRAM_SEED_HANDLES: Record<string, string> = {
  "2 engel & charlie": "@2engelundcharlie",
  "47_kö11sch": "@47_koe11sch",
  "achim petry": "@achimpetry",
  "aileen sager": "@aileen_sgr",
  "ak ausserkontrolle": "@akausserkontrolle",
  "aleks schmidt": "@aleksschmidtlive",
  "alex engel": "@alexengelmusic",
  "ali bumaye": "@alibumaye",
  "aline jost": "@aline_jost_diraimondo",
  "almklausi": "@almklausi",
  "andi latte": "@andi_latte_musik",
  "andi schiebt anders": "@andischiebtanders",
  "andreas maintz": "@andreasmaintz",
  "anna-maria zimmermann": "@amz_welt",
  "annabel anderson": "@annabelandersonmusic",
  "annemarie eilfeld": "@annemarie_eilfeld",
  "anny": "@annyoffiziell",
  "asphalt anton": "@asphaltanton_official",
  "axel aus der hohl": "@axelausderhohl",
  "bääm": "@baeaemband",
  "balkonultra": "@balkonultra",
  "banjee": "@dj_banjee",
  "basic gina": "@basic_gina",
  "beng k.o.x.": "@beng_k.o.x_offiziell",
  "bierkapitän": "@bierkapitaen",
  "breitner": "@breitner_official",
  "calvin kleinen": "@alvinkleinen",
  "capital bra": "@capital_bra",
  "caro winter": "@carowinter.music",
  "carolina": "@carolinapeukmann",
  "chanelle": "@chanelleofficial_",
  "christian franke": "@christian_franke_offiziell_",
  "claudia jung": "@jung.claudia",
  "cosimo": "@cosimoofficial",
  "deejay biene": "@deejay_biene_offiziell",
  "der zipfelbube": "@der.zipfelbube",
  "desiree hansen": "@desireehansen",
  "die atzen": "@dieatzen",
  "die draufgänger": "@die_draufgaenger",
  "die goldjungs": "@goldjungsmusik",
  "die jungen zillertaler": "@_die_jungen_zillertaler___",
  "die tünnesse": "@die.tuennesse",
  "dj aaron": "@dj_aaron_mallorca",
  "dj düse": "@dj_duese",
  "dj ötzi double maik leutner": "@maikleutner",
  "dj robin": "@djrobin1996",
  "don francis": "@don_francis_original",
  "dopebwoy": "@dopebwoy",
  "dorfrocker": "@dorfrocker_official",
  "dragan": "@dragan_autohaendler_von_rtl",
  "emanuel bento": "@emanuelbento_offiziell",
  "fabbel": "@fabbel_offiziell",
  "fabi fiesta": "@dj_fabifiesta",
  "fabian farell": "@fabianfarell",
  "felix harrer": "@felix.harrer.official",
  "finch": "@finch",
  "fire squad": "@firesquad_original",
  "flobo": "@flobo_official",
  "framax": "@framax.music",
  "fräulein süss": "@frauleinsuess",
  "frenzy": "@frenzy_offiziell",
  "girlsclub": "@girlsclub_officialpage",
  "haftbefehl": "@haftbefehl",
  "halodriz": "@halodriz",
  "hannes": "@hannes.kann.es.official",
  "hbz": "@hbzmusic",
  "heino": "@heino.offiziell",
  "housekasper": "@housekasper",
  "idaly": "@idaly",
  "ikke hüftgold": "@ikkehueftgold",
  "ina colada": "@ina_colada_offiziell",
  "ingo ohne flamingo": "@ingo_ohne_flamingo_official",
  "inseljung": "@inseljung_offiziell",
  "isa bella": "@isa_bella__official",
  "isi glück": "@isi_glueck",
  "jack gelee": "@jack_gelee",
  "jason derulo": "@jasonderulo",
  "jebroer": "@jebroer",
  "jessi.kay": "@jessi_.kay",
  "josylvio": "@josylvio",
  "julian benz": "@julianbenz_offiziell",
  "julian sommer": "@juliansommer",
  "juliano": "@julianofernandezz",
  "jürgen milski": "@juergen.milski",
  "jürgen peter": "@juergenpetermaryjane",
  "justin flieger": "@justin_flieger",
  "kati zucker": "@katizucker",
  "kay bang": "@kay_bang_offiziell",
  "kikii": "@kikiiiree",
  "killermichel": "@killermichel",
  "kings of günter": "@kingsofguenter",
  "knossi": "@knossi",
  "komaoma": "@koma.oma_offiziell",
  "kreisligalegende": "@kreisligalegende_offiziell",
  "kriss": "@krissmusics",
  "küchenmeister": "@m.kuechenmeister",
  "lala lacht": "@lala_lacht",
  "le shuuk": "@leshuuk",
  "leon machere": "@leonmachere",
  "leza": "@lezasmusic",
};

export const RELEASE_ARTIST_INSTAGRAM_SEED_LABELS: Record<string, string> = {
  "2 engel & charlie": "2 Engel & Charlie",
  "47_kö11sch": "47_KÖ11SCH",
  "achim petry": "Achim Petry",
  "aileen sager": "Aileen Sager",
  "ak ausserkontrolle": "AK Ausserkontrolle",
  "aleks schmidt": "Aleks Schmidt",
  "alex engel": "Alex Engel",
  "ali bumaye": "Ali Bumaye",
  "aline jost": "Aline Jost",
  "almklausi": "Almklausi",
  "andi latte": "Andi Latte",
  "andi schiebt anders": "Andi Schiebt Anders",
  "andreas maintz": "Andreas Maintz",
  "anna-maria zimmermann": "Anna-Maria Zimmermann",
  "annabel anderson": "Annabel Anderson",
  "annemarie eilfeld": "Annemarie Eilfeld",
  "anny": "Anny",
  "asphalt anton": "Asphalt Anton",
  "axel aus der hohl": "Axel aus der Hohl",
  "bääm": "BÄÄM",
  "balkonultra": "Balkonultra",
  "banjee": "Banjee",
  "basic gina": "Basic Gina",
  "beng k.o.x.": "Beng K.O.X.",
  "bierkapitän": "Bierkapitän",
  "breitner": "Breitner",
  "calvin kleinen": "Calvin Kleinen",
  "capital bra": "Capital Bra",
  "caro winter": "Caro Winter",
  "carolina": "Carolina",
  "chanelle": "Chanelle",
  "christian franke": "Christian Franke",
  "claudia jung": "Claudia Jung",
  "cosimo": "Cosimo",
  "deejay biene": "DeeJay Biene",
  "der zipfelbube": "Der Zipfelbube",
  "desiree hansen": "Desiree Hansen",
  "die atzen": "Die Atzen",
  "die draufgänger": "Die Draufgänger",
  "die goldjungs": "Die Goldjungs",
  "die jungen zillertaler": "Die jungen Zillertaler",
  "die tünnesse": "Die Tünnesse",
  "dj aaron": "DJ Aaron",
  "dj düse": "DJ Düse",
  "dj ötzi double maik leutner": "DJ Ötzi Double Maik Leutner",
  "dj robin": "DJ Robin",
  "don francis": "Don Francis",
  "dopebwoy": "Dopebwoy",
  "dorfrocker": "Dorfrocker",
  "dragan": "Dragan",
  "emanuel bento": "Emanuel Bento",
  "fabbel": "Fabbel",
  "fabi fiesta": "Fabi Fiesta",
  "fabian farell": "Fabian Farell",
  "felix harrer": "Felix Harrer",
  "finch": "Finch",
  "fire squad": "Fire Squad",
  "flobo": "Flobo",
  "framax": "Framax",
  "fräulein süss": "Fräulein Süss",
  "frenzy": "Frenzy",
  "girlsclub": "Girlsclub",
  "haftbefehl": "Haftbefehl",
  "halodriz": "Halodriz",
  "hannes": "Hannes",
  "hbz": "HBz",
  "heino": "Heino",
  "housekasper": "Housekasper",
  "idaly": "Idaly",
  "ikke hüftgold": "Ikke Hüftgold",
  "ina colada": "Ina Colada",
  "ingo ohne flamingo": "Ingo ohne Flamingo",
  "inseljung": "Inseljung",
  "isa bella": "Isa Bella",
  "isi glück": "Isi Glück",
  "jack gelee": "Jack Gelee",
  "jason derulo": "Jason Derulo",
  "jebroer": "Jebroer",
  "jessi.kay": "Jessi.Kay",
  "josylvio": "Josylvio",
  "julian benz": "Julian Benz",
  "julian sommer": "Julian Sommer",
  "juliano": "Juliano",
  "jürgen milski": "Jürgen Milski",
  "jürgen peter": "Jürgen Peter",
  "justin flieger": "Justin Flieger",
  "kati zucker": "Kati Zucker",
  "kay bang": "Kay Bang",
  "kikii": "Kikii",
  "killermichel": "Killermichel",
  "kings of günter": "Kings of Günter",
  "knossi": "Knossi",
  "komaoma": "KomaOma",
  "kreisligalegende": "Kreisligalegende",
  "kriss": "Kriss",
  "küchenmeister": "Küchenmeister",
  "lala lacht": "Lala Lacht",
  "le shuuk": "Le Shuuk",
  "leon machere": "Leon Machere",
  "leza": "Leza",
};
