'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { AdminRoundSummary, Round } from '@/lib/releaseVotingShared';
import { formatAdminDateTime } from '@/lib/adminUi';
import { PageHeader, StatCard } from './AdminUi';

type Filter = 'all' | 'counted' | 'review' | 'excluded' | 'unverified';
type Participant = AdminRoundSummary['participants'][number];

function status(participant: Participant) {
  if (!participant.isVerified) return { key: 'unverified' as const, label: 'Unbestätigt' };
  if (participant.integrityStatus === 'excluded') return { key: 'excluded' as const, label: 'Ausgeschlossen' };
  if (!participant.isCounted || participant.integrityStatus === 'review') return { key: 'review' as const, label: 'Bestätigt · nicht gewertet' };
  return { key: 'counted' as const, label: participant.integrityStatus === 'approved' ? 'Gewertet · geprüft' : 'Gewertet' };
}

function shortHash(value?: string | null) { return value ? `${value.slice(0, 8)}…` : '—'; }

export default function PublicVotesManager({ round, summary, initialFilter = 'all' }: { round: Round; summary: AdminRoundSummary; initialFilter?: Filter }) {
  const router = useRouter();
  const [filter, setFilter] = useState<Filter>(initialFilter); const [selected, setSelected] = useState<Set<string>>(() => new Set()); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<{ type: 'ok' | 'error'; text: string } | null>(null);
  const filtered = useMemo(() => filter === 'all' ? summary.participants : summary.participants.filter((participant) => status(participant).key === filter), [filter, summary.participants]);
  const selectable = filtered.filter((participant) => participant.isVerified).map((participant) => participant.voteId); const allVisibleSelected = selectable.length > 0 && selectable.every((id) => selected.has(id));
  function setMany(ids: string[], checked: boolean) { setSelected((current) => { const next = new Set(current); ids.forEach((id) => checked ? next.add(id) : next.delete(id)); return next; }); }
  function toggle(id: string, checked: boolean) { setMany([id], checked); }
  async function mutate(action: 'count' | 'exclude', voteIds: string[]) { if (!voteIds.length) return; const verb = action === 'count' ? 'werten' : 'ausschließen'; if (!window.confirm(`${voteIds.length} ${voteIds.length === 1 ? 'Stimme' : 'Stimmen'} wirklich ${verb}?`)) return; setBusy(true); setMessage(null); try { const response = await fetch('/api/admin/vote-status', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ voteIds, action }) }); const data = await response.json().catch(() => null); if (!response.ok || !data?.ok) throw new Error(data?.error || 'Status konnte nicht geändert werden.'); setSelected(new Set()); setMessage({ type: 'ok', text: `${voteIds.length} ${voteIds.length === 1 ? 'Stimme wurde' : 'Stimmen wurden'} aktualisiert.` }); router.refresh(); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Unbekannter Fehler.' }); } finally { setBusy(false); } }
  function copyEmails(verifiedOnly: boolean) { const emails = summary.participants.filter((participant) => !verifiedOnly || participant.isVerified).map((participant) => participant.email.trim()).filter(Boolean).filter((email, index, list) => list.indexOf(email) === index); if (!emails.length) { setMessage({ type: 'error', text: 'Keine passenden E-Mail-Adressen gefunden.' }); return; } void navigator.clipboard?.writeText(emails.join('\n')); setMessage({ type: 'ok', text: verifiedOnly ? 'Bestätigte E-Mail-Adressen kopiert.' : 'Alle E-Mail-Adressen kopiert.' }); }

  return <main>
    <PageHeader eyebrow={<a href={`/admin/release-voting/${round.id}`}>← Zur Umfrage</a>} title="Publikumsstimmen verwalten" description={round.title} actions={<a className="ks-button secondary" href={`/release-voting/${round.slug}`} target="_blank" rel="noreferrer">Publikumsseite öffnen</a>} />
    {message && <div className={`notice ${message.type === 'ok' ? 'success' : 'error'}`}>{message.text}</div>}
    <section className="ks-stats-grid dashboard"><StatCard label="Insgesamt" value={summary.totalVotes} /><StatCard label="Bestätigt" value={summary.confirmedVotes} /><StatCard label="Gewertet" value={summary.countedVotes} tone="success" /><StatCard label="Nicht bestätigt" value={summary.unverifiedVotes} tone="warning" /><StatCard label="In Prüfung" value={summary.reviewVotes} tone="warning" /><StatCard label="Ausgeschlossen" value={summary.excludedVotes} tone="danger" /></section>
    <section className="ks-card">
      <div className="ks-table-toolbar votes"><div className="ks-filter-tabs">{([['all', `Alle ${summary.totalVotes}`], ['counted', `Gewertet ${summary.countedVotes}`], ['review', `Prüfung ${summary.reviewVotes}`], ['excluded', `Ausgeschlossen ${summary.excludedVotes}`], ['unverified', `Unbestätigt ${summary.unverifiedVotes}`]] as Array<[Filter, string]>).map(([key, label]) => <button type="button" key={key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{label}</button>)}</div><div className="ks-inline-actions"><button className="ks-button small secondary" type="button" onClick={() => copyEmails(false)}>Alle E-Mails</button><button className="ks-button small secondary" type="button" onClick={() => copyEmails(true)}>Bestätigte E-Mails</button></div></div>
      <div className="ks-bulk-toolbar"><div><strong>{selected.size} ausgewählt</strong><button type="button" onClick={() => setSelected(new Set())} disabled={!selected.size}>Auswahl aufheben</button></div><div><button className="ks-button success" type="button" disabled={!selected.size || busy} onClick={() => void mutate('count', [...selected])}>Ausgewählte werten</button><button className="ks-button danger" type="button" disabled={!selected.size || busy} onClick={() => void mutate('exclude', [...selected])}>Ausgewählte ausschließen</button></div></div>
      <div className="ks-table-scroll vote-manager"><table className="ks-table votes"><thead><tr><th><input type="checkbox" aria-label="Alle sichtbaren bestätigten Stimmen auswählen" checked={allVisibleSelected} disabled={!selectable.length} onChange={(event) => setMany(selectable, event.target.checked)} /></th><th>Status</th><th>Prüfhinweis</th><th>Name</th><th>E-Mail</th><th>Verbindung</th><th>Abgestimmt</th><th>Bestätigt</th><th>ZONK</th><th></th></tr></thead><tbody>{filtered.map((participant) => { const itemStatus = status(participant); return <tr key={participant.voteId} className={itemStatus.key === 'review' ? 'needs-review' : ''}><td><input type="checkbox" checked={selected.has(participant.voteId)} disabled={!participant.isVerified} onChange={(event) => toggle(participant.voteId, event.target.checked)} aria-label={`Stimme von ${participant.email || participant.name || 'Teilnehmer'} auswählen`} /></td><td><span className={`ks-vote-status ${itemStatus.key}`}>{itemStatus.label}</span></td><td className="ks-reasons">{participant.integrityReasons.length ? participant.integrityReasons.map((reason) => <span key={reason}>! {reason}</span>) : 'Keine Auffälligkeit'}</td><td>{participant.name || '—'}</td><td>{participant.email ? <a href={`mailto:${participant.email}`}>{participant.email}</a> : '—'}{participant.emailDomain && <small>{participant.emailDomain}</small>}</td><td title={participant.ipHash || ''}>{shortHash(participant.ipHash)}{participant.sameIpVotes > 1 && <small>{participant.sameIpVotes} gleicher Hash</small>}</td><td>{formatAdminDateTime(participant.votedAt)}</td><td>{formatAdminDateTime(participant.verifiedAt)}</td><td>{participant.zonkSong || '—'}</td><td><div className="ks-inline-actions">{participant.isVerified && itemStatus.key !== 'counted' && <button className="ks-button small secondary" type="button" onClick={() => void mutate('count', [participant.voteId])}>Werten</button>}{itemStatus.key !== 'excluded' && <button className="ks-button small secondary" type="button" onClick={() => void mutate('exclude', [participant.voteId])}>Ausschließen</button>}</div></td></tr>; })}{!filtered.length && <tr><td colSpan={10} className="ks-table-empty">Keine Stimmen in diesem Filter.</td></tr>}</tbody></table></div>
    </section>
  </main>;
}
