'use client';

import type { Round } from '@/lib/releaseVotingShared';
import { dateTimeLocalToIso, toDateTimeLocal } from '@/lib/adminUi';

type Post = (url: string, body: unknown) => Promise<boolean>;

export default function RoundSettingsPanel({ round, isCurrentDj, post }: { round: Round; isCurrentDj: boolean; post: Post }) {
  return <details className="ks-card ks-disclosure settings" id="round-settings"><summary>Umfrage-Einstellungen bearbeiten</summary><form className="ks-form ks-disclosure-body" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void post('/api/admin/round', { id: round.id, onlyUpdate: true, title: form.get('title'), slug: form.get('slug'), description: form.get('description'), status: form.get('status'), startsAt: dateTimeLocalToIso(form.get('startsAt')), endsAt: dateTimeLocalToIso(form.get('endsAt')), placesCount: Number(form.get('placesCount') || 12), spotifyPlaylistId: form.get('spotifyPlaylistId'), isCurrent: form.get('isCurrent') === 'on', isCurrentDj: form.get('isCurrentDj') === 'on', isPublicResults: form.get('isPublicResults') === 'on' }); }}>
    <label>Titel<input name="title" defaultValue={round.title} /></label><div className="ks-form-row two"><label>Slug<input name="slug" defaultValue={round.slug} /></label><label>Status<select name="status" defaultValue={round.status}><option value="draft">Geplant</option><option value="live">Aktiv</option><option value="ended">Abgeschlossen</option></select></label></div><label>Beschreibung<textarea name="description" defaultValue={round.description || ''} rows={3} /></label><div className="ks-form-row three"><label>Start<input name="startsAt" type="datetime-local" defaultValue={toDateTimeLocal(round.starts_at)} /></label><label>Ende<input name="endsAt" type="datetime-local" defaultValue={toDateTimeLocal(round.ends_at)} /></label><label>Plätze<input name="placesCount" type="number" min="1" max="50" defaultValue={round.places_count || 12} /></label></div><label>Spotify-Playlist-ID oder URL<input name="spotifyPlaylistId" defaultValue={round.spotify_playlist_id || ''} /></label><div className="ks-check-stack"><label><input type="checkbox" name="isCurrent" defaultChecked={round.is_current} /> Öffentliche Haupt-Abstimmung</label><label><input type="checkbox" name="isCurrentDj" defaultChecked={isCurrentDj} /> Aktuelles DJ-Voting</label><label><input type="checkbox" name="isPublicResults" defaultChecked={round.is_public_results} /> Ergebnis öffentlich anzeigen</label></div><div className="ks-form-actions"><button className="ks-button primary" type="submit">Einstellungen speichern</button></div>
  </form></details>;
}
